### ISSUE TITLE
Motion widget failing

### ISSUE THREAD

**Issue by PiWi56** [RubendeBruin/DAVE#153]
Motion Widget is failing when called from the GUI 

problem in main.py and widget_modeshapes.py
```
Traceback (most recent call last):
  File "C:\Users\pw\AppData\Local\anaconda3\envs\DAVE\Lib\site-packages\DAVE\gui\main.py", line 1195, in <lambda>
    lambda *args, name=d.ID: self.activate_dockgroup(name)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pw\AppData\Local\anaconda3\envs\DAVE\Lib\site-packages\DAVE\gui\main.py", line 1231, in activate_dockgroup
    wanted_docks = [self.get_dock(name) for name in group.dock_widgets]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pw\AppData\Local\anaconda3\envs\DAVE\Lib\site-packages\DAVE\gui\main.py", line 1231, in <listcomp>
    wanted_docks = [self.get_dock(name) for name in group.dock_widgets]
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pw\AppData\Local\anaconda3\envs\DAVE\Lib\site-packages\DAVE\gui\main.py", line 2984, in get_dock
    d.guiProcessEvent(guiEventType.FULL_UPDATE)
  File "C:\Users\pw\AppData\Local\anaconda3\envs\DAVE\Lib\site-packages\DAVE\gui\widget_modeshapes.py", line 71, in guiProcessEvent
    self.fill_result_table()
  File "C:\Users\pw\AppData\Local\anaconda3\envs\DAVE\Lib\site-packages\DAVE\gui\widget_modeshapes.py", line 173, in fill_result_table
    summary = DAVE.frequency_domain.dynamics_summary_data(self.guiScene)
              ^^^^
NameError: name 'DAVE' is not defined
```

**Comment by RubendeBruin** [comment]
Hi PiWi56, sorry for not getting back to you sooner. 
I can not reproduce your issue.

Are you running from source or are you using the pre-compiled version?
